# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.0410, 0.3315, 0.7746, 0.7780, 0.7395, 0.4077, 0.7338],
        [0.1679, 0.6673, 0.3770, 0.0827, 0.2382, 0.2339, 0.1437],
        [0.4630, 0.5700, 0.7308, 0.0788, 0.3291, 0.9646, 0.5626],
        [0.9848, 0.1485, 0.8896, 0.6024, 0.6378, 0.8448, 0.8658],
        [0.0071, 0.7249, 0.6371, 0.9508, 0.2061, 0.2190, 0.4356],
        [0.0439, 0.3124, 0.2788, 0.7794, 0.6601, 0.1679, 0.3595],
        [0.3346, 0.2301, 0.3559, 0.1989, 0.3112, 0.4528, 0.1932]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
y = torch.rand(1, 7)

# Perform matrix multiplication
z = torch.matmul(x, y.T)
z

tensor([[1.8176],
        [0.5743],
        [0.9871],
        [1.9037],
        [1.4693],
        [1.4578],
        [0.7387]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors


# Matrix multiply tensors
x = torch.matmul(torch.rand(7, 7), torch.rand(1, 7).T)
x, x.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
x = torch.rand(2, 3).to(device)
y = torch.rand(2, 3).to(device)
x, y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:
# Perform matmul on tensor_A and tensor_B
new_tensor = torch.matmul(x, y.T)
new_tensor, new_tensor.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
max = new_tensor.max()
print(max)

# Find min
min = new_tensor.min()
print(min)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [23]:
# Find arg max
argmax = new_tensor.argmax()
print(argmax)

# Find arg min
argmin = new_tensor.argmin()
print(argmin)

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [40]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand(1, 1, 1, 10)

# Remove single dimensions
y = x.squeeze()

# Print out tensors and their shapes
print(x, x.shape)
print(y, y.shape)

z = x.permute(0, 2, 3, 1)
print(z, z.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
tensor([[[[0.5349],
          [0.1988],
          [0.6592],
          [0.6569],
          [0.2328],
          [0.4251],
          [0.2071],
          [0.6297],
          [0.3653],
          [0.8513]]]]) torch.Size([1, 1, 10, 1])
